## 一、介绍

Polars 是一个用于操作结构化数据的高性能 DataFrame 库，由于 Polars 是从0开始用Rust编写，紧密与机器结合。其矢量化和列式处理可在现代处理器上实现缓存一致性算法和高性能。如果您经常使用 pandas，那么用起 Polars 会感觉很轻松，可以说是平替 Pandas 最有潜质的包。

Polars 在独立的 TPCH 基准测试中与其他几个解决方案进行了基准测试。该基准测试旨在复制实践中使用的数据整理操作。由于其并行执行引擎、高效算法以及 SIMD（单指令、多数据）矢量化的使用，Polars 轻松胜过其他解决方案。**与pandas相比，它可以实现30倍以上的性能提升**。



Polars 的目标是提供一个闪电般快速的`DataFrame`库：

- 利用机器上所有可用的内核。
- 优化查询以减少不必要的工作/内存分配。
- 处理比可用 RAM 大得多的数据集。
- 拥有一致且可预测的 API。
- 具有严格的架构（在运行查询之前应该知道数据类型）。

<br>

[User guide: https://pola-rs.github.io/polars/user-guide/](https://pola-rs.github.io/polars/user-guide/)
[API reference: https://pola-rs.github.io/polars/py-polars/html/reference/io.html](https://pola-rs.github.io/polars/py-polars/html/reference/io.html)

<br>

打开命令行， 执行  polars 安装命令

In [ ]:
!pip3 install 'polars[all]'


## 二、数据读写

Polars 读写数据支持

- 常见的数据文件，如 csv、xlsx、json、parquet ；
- 云存储，如 S3、Azure Blob, BigQuery； 
- 数据库，如postgres、mysql



咱们主要分享常见的代码操作

In [38]:
import polars as pl
from datetime import datetime

df = pl.DataFrame(
    {
        "idx": [1, 2, 3, 4],
        "name": ["张三", "李四", "王五", "赵六"],
        "birthday": [
            datetime(2009, 5, 1),
            datetime(2005, 10, 15),
            datetime(2000, 12, 31),
            datetime(1995, 6, 15),
        ],
        "gender": ["男", "男", "男", "女"],
        "bio": ["好好学习，天天向上", 
                "泰难了", 
                "学习有毛用", 
                "躺平ing"],
    }
)

#存入csv、excel、json、parquet
df.write_csv("data.csv")
df.write_excel("data.xlsx")
df.write_json("data.json")
df.write_parquet("data.parquet")


df

shape: (4, 5)
┌─────┬──────┬─────────────────────┬────────┬────────────────────┐
│ idx ┆ name ┆ birthday            ┆ gender ┆ bio                │
│ --- ┆ ---  ┆ ---                 ┆ ---    ┆ ---                │
│ i64 ┆ str  ┆ datetime[μs]        ┆ str    ┆ str                │
╞═════╪══════╪═════════════════════╪════════╪════════════════════╡
│ 1   ┆ 张三 ┆ 2009-05-01 00:00:00 ┆ 男     ┆ 好好学习，天天向上 │
│ 2   ┆ 李四 ┆ 2005-10-15 00:00:00 ┆ 男     ┆ 泰难了             │
│ 3   ┆ 王五 ┆ 2000-12-31 00:00:00 ┆ 男     ┆ 学习有毛用         │
│ 4   ┆ 赵六 ┆ 1995-06-15 00:00:00 ┆ 女     ┆ 躺平ing            │
└─────┴──────┴─────────────────────┴────────┴────────────────────┘

In [39]:
df_csv = pl.read_csv('data.csv')
df_xlsx = pl.read_excel('data.xlsx')

df_csv

shape: (4, 5)
┌─────┬──────┬────────────────────────────┬────────┬────────────────────┐
│ idx ┆ name ┆ birthday                   ┆ gender ┆ bio                │
│ --- ┆ ---  ┆ ---                        ┆ ---    ┆ ---                │
│ i64 ┆ str  ┆ str                        ┆ str    ┆ str                │
╞═════╪══════╪════════════════════════════╪════════╪════════════════════╡
│ 1   ┆ 张三 ┆ 2009-05-01T00:00:00.000000 ┆ 男     ┆ 好好学习，天天向上 │
│ 2   ┆ 李四 ┆ 2005-10-15T00:00:00.000000 ┆ 男     ┆ 泰难了             │
│ 3   ┆ 王五 ┆ 2000-12-31T00:00:00.000000 ┆ 男     ┆ 学习有毛用         │
│ 4   ┆ 赵六 ┆ 1995-06-15T00:00:00.000000 ┆ 女     ┆ 躺平ing            │
└─────┴──────┴────────────────────────────┴────────┴────────────────────┘

In [40]:
df_json = pl.read_json("data.json")
df_parquet = pl.read_parquet("data.parquet")

df_json

shape: (4, 5)
┌─────┬──────┬─────────────────────┬────────┬────────────────────┐
│ idx ┆ name ┆ birthday            ┆ gender ┆ bio                │
│ --- ┆ ---  ┆ ---                 ┆ ---    ┆ ---                │
│ i64 ┆ str  ┆ datetime[μs]        ┆ str    ┆ str                │
╞═════╪══════╪═════════════════════╪════════╪════════════════════╡
│ 1   ┆ 张三 ┆ 2009-05-01 00:00:00 ┆ 男     ┆ 好好学习，天天向上 │
│ 2   ┆ 李四 ┆ 2005-10-15 00:00:00 ┆ 男     ┆ 泰难了             │
│ 3   ┆ 王五 ┆ 2000-12-31 00:00:00 ┆ 男     ┆ 学习有毛用         │
│ 4   ┆ 赵六 ┆ 1995-06-15 00:00:00 ┆ 女     ┆ 躺平ing            │
└─────┴──────┴─────────────────────┴────────┴────────────────────┘

## 三、Expressions表达式

`Expressions`是Polars的核心功能， `expressions` 既可以解决简单的查询，又可以轻松扩展到复杂的查询。下面是 polars 的基本表达式

- select
- filter
- with_columns
- grouby 

### 3.1 select

In [46]:
df.select(
    pl.col("name"), 
    pl.col("birthday"),
)

shape: (4, 2)
┌──────┬─────────────────────┐
│ name ┆ birthday            │
│ ---  ┆ ---                 │
│ str  ┆ datetime[μs]        │
╞══════╪═════════════════════╡
│ 张三 ┆ 2009-05-01 00:00:00 │
│ 李四 ┆ 2005-10-15 00:00:00 │
│ 王五 ┆ 2000-12-31 00:00:00 │
│ 赵六 ┆ 1995-06-15 00:00:00 │
└──────┴─────────────────────┘

In [45]:
df.select(
    pl.col("name").alias('姓名'),
    pl.col("birthday").alias('生日')
)

shape: (4, 2)
┌──────┬─────────────────────┐
│ 姓名 ┆ 生日                │
│ ---  ┆ ---                 │
│ str  ┆ datetime[μs]        │
╞══════╪═════════════════════╡
│ 张三 ┆ 2009-05-01 00:00:00 │
│ 李四 ┆ 2005-10-15 00:00:00 │
│ 王五 ┆ 2000-12-31 00:00:00 │
│ 赵六 ┆ 1995-06-15 00:00:00 │
└──────┴─────────────────────┘

In [118]:
pl.col("name", "birthday")

In [109]:
df.select(
    pl.col("name", "birthday")
)

shape: (4, 2)
┌──────┬─────────────────────┐
│ name ┆ birthday            │
│ ---  ┆ ---                 │
│ str  ┆ datetime[μs]        │
╞══════╪═════════════════════╡
│ 张三 ┆ 2009-05-01 00:00:00 │
│ 李四 ┆ 2005-10-15 00:00:00 │
│ 王五 ┆ 2000-12-31 00:00:00 │
│ 赵六 ┆ 1995-06-15 00:00:00 │
└──────┴─────────────────────┘

In [110]:
df.select(
    ["name", "birthday"]
)

shape: (4, 2)
┌──────┬─────────────────────┐
│ name ┆ birthday            │
│ ---  ┆ ---                 │
│ str  ┆ datetime[μs]        │
╞══════╪═════════════════════╡
│ 张三 ┆ 2009-05-01 00:00:00 │
│ 李四 ┆ 2005-10-15 00:00:00 │
│ 王五 ┆ 2000-12-31 00:00:00 │
│ 赵六 ┆ 1995-06-15 00:00:00 │
└──────┴─────────────────────┘

In [64]:
df["name"]
df[["name"]]

shape: (4, 1)
┌──────┐
│ name │
│ ---  │
│ str  │
╞══════╡
│ 张三 │
│ 李四 │
│ 王五 │
│ 赵六 │
└──────┘

In [63]:
df.select(["name"])
#df.select("name")

shape: (4, 1)
┌──────┐
│ name │
│ ---  │
│ str  │
╞══════╡
│ 张三 │
│ 李四 │
│ 王五 │
│ 赵六 │
└──────┘

In [108]:
df.with_columns(
    pl.col('name').alias('姓名')
)

shape: (4, 6)
┌─────┬──────┬─────────────────────┬────────┬────────────────────┬──────┐
│ idx ┆ name ┆ birthday            ┆ gender ┆ bio                ┆ 姓名 │
│ --- ┆ ---  ┆ ---                 ┆ ---    ┆ ---                ┆ ---  │
│ i64 ┆ str  ┆ datetime[μs]        ┆ str    ┆ str                ┆ str  │
╞═════╪══════╪═════════════════════╪════════╪════════════════════╪══════╡
│ 1   ┆ 张三 ┆ 2009-05-01 00:00:00 ┆ 男     ┆ 好好学习，天天向上 ┆ 张三 │
│ 2   ┆ 李四 ┆ 2005-10-15 00:00:00 ┆ 男     ┆ 泰难了             ┆ 李四 │
│ 3   ┆ 王五 ┆ 2000-12-31 00:00:00 ┆ 男     ┆ 学习有毛用         ┆ 王五 │
│ 4   ┆ 赵六 ┆ 1995-06-15 00:00:00 ┆ 女     ┆ 躺平ing            ┆ 赵六 │
└─────┴──────┴─────────────────────┴────────┴────────────────────┴──────┘

In [66]:
df.filter(df['birthday']>datetime(2000, 1, 1))

shape: (3, 5)
┌─────┬──────┬─────────────────────┬────────┬────────────────────┐
│ idx ┆ name ┆ birthday            ┆ gender ┆ bio                │
│ --- ┆ ---  ┆ ---                 ┆ ---    ┆ ---                │
│ i64 ┆ str  ┆ datetime[μs]        ┆ str    ┆ str                │
╞═════╪══════╪═════════════════════╪════════╪════════════════════╡
│ 1   ┆ 张三 ┆ 2009-05-01 00:00:00 ┆ 男     ┆ 好好学习，天天向上 │
│ 2   ┆ 李四 ┆ 2005-10-15 00:00:00 ┆ 男     ┆ 泰难了             │
│ 3   ┆ 王五 ┆ 2000-12-31 00:00:00 ┆ 男     ┆ 学习有毛用         │
└─────┴──────┴─────────────────────┴────────┴────────────────────┘

In [75]:
df['birthday'>datetime(2000, 1, 1)]

TypeError: '>' not supported between instances of 'str' and 'datetime.datetime'

In [78]:
#df[pl.col('birthday')>datetime(2000, 1, 1)]


df.filter(pl.col('birthday')>datetime(2000, 1, 1))

shape: (3, 5)
┌─────┬──────┬─────────────────────┬────────┬────────────────────┐
│ idx ┆ name ┆ birthday            ┆ gender ┆ bio                │
│ --- ┆ ---  ┆ ---                 ┆ ---    ┆ ---                │
│ i64 ┆ str  ┆ datetime[μs]        ┆ str    ┆ str                │
╞═════╪══════╪═════════════════════╪════════╪════════════════════╡
│ 1   ┆ 张三 ┆ 2009-05-01 00:00:00 ┆ 男     ┆ 好好学习，天天向上 │
│ 2   ┆ 李四 ┆ 2005-10-15 00:00:00 ┆ 男     ┆ 泰难了             │
│ 3   ┆ 王五 ┆ 2000-12-31 00:00:00 ┆ 男     ┆ 学习有毛用         │
└─────┴──────┴─────────────────────┴────────┴────────────────────┘

In [84]:
help(pl.col('birthday').dt)

Help on ExprDateTimeNameSpace in module polars.expr.datetime object:

class ExprDateTimeNameSpace(builtins.object)
 |  ExprDateTimeNameSpace(expr: 'Expr')
 |
 |  Namespace for datetime related expressions.
 |
 |  Methods defined here:
 |
 |  __init__(self, expr: 'Expr')
 |      Initialize self.  See help(type(self)) for accurate signature.
 |
 |  base_utc_offset(self) -> 'Expr'
 |      Base offset from UTC.
 |
 |      This is usually constant for all datetimes in a given time zone, but
 |      may vary in the rare case that a country switches time zone, like
 |      Samoa (Apia) did at the end of 2011.
 |
 |      Returns
 |      -------
 |      Expr
 |          Expression of data type :class:`Duration`.
 |
 |      See Also
 |      --------
 |      Expr.dt.dst_offset : Daylight savings offset from UTC.
 |
 |      Examples
 |      --------
 |      >>> from datetime import datetime
 |      >>> df = pl.DataFrame(
 |      ...     {
 |      ...         "ts": [datetime(2011, 12, 29), datetime(2012, 1, 1)],
 |      ...     }
 |      ... )
 |      >>> df = df.with_columns(pl.col("ts").dt.replace_time_zone("Pacific/Apia"))
 |      >>> df.with_columns(pl.col("ts").dt.base_utc_offset().alias("base_utc_offset"))
 |      shape: (2, 2)
 |      ┌────────────────────────────┬─────────────────┐
 |      │ ts                         ┆ base_utc_offset │
 |      │ ---                        ┆ ---             │
 |      │ datetime[μs, Pacific/Apia] ┆ duration[ms]    │
 |      ╞════════════════════════════╪═════════════════╡
 |      │ 2011-12-29 00:00:00 -10    ┆ -11h            │
 |      │ 2012-01-01 00:00:00 +14    ┆ 13h             │
 |      └────────────────────────────┴─────────────────┘
 |
 |  cast_time_unit(self, time_unit: 'TimeUnit') -> 'Expr'
 |      Cast the underlying data to another time unit. This may lose precision.
 |
 |      Parameters
 |      ----------
 |      time_unit : {'ns', 'us', 'ms'}
 |          Time unit for the `Datetime` expression.
 |
 |      Examples
 |      --------
 |      >>> from datetime import datetime
 |      >>> df = pl.DataFrame(
 |      ...     {
 |      ...         "date": pl.datetime_range(
 |      ...             datetime(2001, 1, 1), datetime(2001, 1, 3), "1d", eager=True
 |      ...         )
 |      ...     }
 |      ... )
 |      >>> df.select(
 |      ...     [
 |      ...         pl.col("date"),
 |      ...         pl.col("date").dt.cast_time_unit("ms").alias("time_unit_ms"),
 |      ...         pl.col("date").dt.cast_time_unit("ns").alias("time_unit_ns"),
 |      ...     ]
 |      ... )
 |      shape: (3, 3)
 |      ┌─────────────────────┬─────────────────────┬─────────────────────┐
 |      │ date                ┆ time_unit_ms        ┆ time_unit_ns        │
 |      │ ---                 ┆ ---                 ┆ ---                 │
 |      │ datetime[μs]        ┆ datetime[ms]        ┆ datetime[ns]        │
 |      ╞═════════════════════╪═════════════════════╪═════════════════════╡
 |      │ 2001-01-01 00:00:00 ┆ 2001-01-01 00:00:00 ┆ 2001-01-01 00:00:00 │
 |      │ 2001-01-02 00:00:00 ┆ 2001-01-02 00:00:00 ┆ 2001-01-02 00:00:00 │
 |      │ 2001-01-03 00:00:00 ┆ 2001-01-03 00:00:00 ┆ 2001-01-03 00:00:00 │
 |      └─────────────────────┴─────────────────────┴─────────────────────┘
 |
 |  combine(self, time: 'dt.time | Expr', time_unit: 'TimeUnit' = 'us') -> 'Expr'
 |      Create a naive Datetime from an existing Date/Datetime expression and a Time.
 |
 |      If the underlying expression is a Datetime then its time component is replaced,
 |      and if it is a Date then a new Datetime is created by combining the two values.
 |
 |      Parameters
 |      ----------
 |      time
 |          A python time literal or polars expression/column that resolves to a time.
 |      time_unit : {'ns', 'us', 'ms'}
 |          Unit of time.
 |
 |      Examples
 |      --------
 |      >>> from datetime import datetime, date, time
 |      >>> df = pl.DataFrame(
 |      ...     {
 |      ...         "dtm": [
 |      ...             datetime(2022, 12, 31, 10, 30, 45),
 |      ...             datetime(2023, 7, 5, 23, 59, 59),
 |      ...         ],
 |      ...         "dt": [date(2022, 10, 10), date(2022, 7, 5)],
 |      ...         "tm": [time(1, 2, 3, 456000), time(7, 8, 9, 101000)],
 |      ...     }
 |      ... )
 |      >>> df
 |      shape: (2, 3)
 |      ┌─────────────────────┬────────────┬──────────────┐
 |      │ dtm                 ┆ dt         ┆ tm           │
 |      │ ---                 ┆ ---        ┆ ---          │
 |      │ datetime[μs]        ┆ date       ┆ time         │
 |      ╞═════════════════════╪════════════╪══════════════╡
 |      │ 2022-12-31 10:30:45 ┆ 2022-10-10 ┆ 01:02:03.456 │
 |      │ 2023-07-05 23:59:59 ┆ 2022-07-05 ┆ 07:08:09.101 │
 |      └─────────────────────┴────────────┴──────────────┘
 |      >>> df.select(
 |      ...     [
 |      ...         pl.col("dtm").dt.combine(pl.col("tm")).alias("d1"),
 |      ...         pl.col("dt").dt.combine(pl.col("tm")).alias("d2"),
 |      ...         pl.col("dt").dt.combine(time(4, 5, 6)).alias("d3"),
 |      ...     ]
 |      ... )
 |      shape: (2, 3)
 |      ┌─────────────────────────┬─────────────────────────┬─────────────────────┐
 |      │ d1                      ┆ d2                      ┆ d3                  │
 |      │ ---                     ┆ ---                     ┆ ---                 │
 |      │ datetime[μs]            ┆ datetime[μs]            ┆ datetime[μs]        │
 |      ╞═════════════════════════╪═════════════════════════╪═════════════════════╡
 |      │ 2022-12-31 01:02:03.456 ┆ 2022-10-10 01:02:03.456 ┆ 2022-10-10 04:05:06 │
 |      │ 2023-07-05 07:08:09.101 ┆ 2022-07-05 07:08:09.101 ┆ 2022-07-05 04:05:06 │
 |      └─────────────────────────┴─────────────────────────┴─────────────────────┘
 |
 |  convert_time_zone(self, time_zone: 'str') -> 'Expr'
 |      Convert to given time zone for an expression of type Datetime.
 |
 |      Parameters
 |      ----------
 |      time_zone
 |          Time zone for the `Datetime` expression.
 |
 |      Examples
 |      --------
 |      >>> from datetime import datetime
 |      >>> df = pl.DataFrame(
 |      ...     {
 |      ...         "date": pl.datetime_range(
 |      ...             datetime(2020, 3, 1),
 |      ...             datetime(2020, 5, 1),
 |      ...             "1mo",
 |      ...             time_zone="UTC",
 |      ...             eager=True,
 |      ...         ),
 |      ...     }
 |      ... )
 |      >>> df.select(
 |      ...     [
 |      ...         pl.col("date"),
 |      ...         pl.col("date")
 |      ...         .dt.convert_time_zone(time_zone="Europe/London")
 |      ...         .alias("London"),
 |      ...     ]
 |      ... )
 |      shape: (3, 2)
 |      ┌─────────────────────────┬─────────────────────────────┐
 |      │ date                    ┆ London                      │
 |      │ ---                     ┆ ---                         │
 |      │ datetime[μs, UTC]       ┆ datetime[μs, Europe/London] │
 |      ╞═════════════════════════╪═════════════════════════════╡
 |      │ 2020-03-01 00:00:00 UTC ┆ 2020-03-01 00:00:00 GMT     │
 |      │ 2020-04-01 00:00:00 UTC ┆ 2020-04-01 01:00:00 BST     │
 |      │ 2020-05-01 00:00:00 UTC ┆ 2020-05-01 01:00:00 BST     │
 |      └─────────────────────────┴─────────────────────────────┘
 |
 |  date(self) -> 'Expr'
 |      Extract date from date(time).
 |
 |      Applies to Date and Datetime columns.
 |
 |      Returns
 |      -------
 |      Expr
 |          Expression of data type :class:`Date`.
 |
 |  datetime(self) -> 'Expr'
 |      Return datetime.
 |
 |      Applies to Datetime columns.
 |
 |      Returns
 |      -------
 |      Expr
 |          Expression of data type :class:`Datetime`.
 |
 |  day(self) -> 'Expr'
 |      Extract day from underlying Date representation.
 |
 |      Applies to Date and Datetime columns.
 |
 |      Returns the day of month starting from 1.
 |      The return value ranges from 1 to 31. (The last day of month differs by months.)
 |
 |      Returns
 |      -------
 |      Expr
 |          Expression of data type :class:`Int8`.
 |
 |      See Also
 |      --------
 |      weekday
 |      ordinal_day
 |
 |      Examples
 |      --------
 |      >>> from datetime import date
 |      >>> df = pl.DataFrame(
 |      ...     {
 |      ...         "date": pl.date_range(
 |      ...             date(2001, 12, 22), date(2001, 12, 25), eager=True
 |      ...         )
 |      ...     }
 |      ... )
 |      >>> df.with_columns(
 |      ...     pl.col("date").dt.weekday().alias("weekday"),
 |      ...     pl.col("date").dt.day().alias("day_of_month"),
 |      ...     pl.col("date").dt.ordinal_day().alias("day_of_year"),
 |      ... )
 |      shape: (4, 4)
 |      ┌────────────┬─────────┬──────────────┬─────────────┐
 |      │ date       ┆ weekday ┆ day_of_month ┆ day_of_year │
 |      │ ---        ┆ ---     ┆ ---          ┆ ---         │
 |      │ date       ┆ i8      ┆ i8           ┆ i16         │
 |      ╞════════════╪═════════╪══════════════╪═════════════╡
 |      │ 2001-12-22 ┆ 6       ┆ 22           ┆ 356         │
 |      │ 2001-12-23 ┆ 7       ┆ 23           ┆ 357         │
 |      │ 2001-12-24 ┆ 1       ┆ 24           ┆ 358         │
 |      │ 2001-12-25 ┆ 2       ┆ 25           ┆ 359         │
 |      └────────────┴─────────┴──────────────┴─────────────┘
 |
 |  days(self) -> 'Expr'
 |      Extract the total days from a Duration type.
 |
 |      .. deprecated:: 0.19.13
 |          Use :meth:`total_days` instead.
 |
 |  dst_offset(self) -> 'Expr'
 |      Additional offset currently in effect (typically due to daylight saving time).
 |
 |      Returns
 |      -------
 |      Expr
 |          Expression of data type :class:`Duration`.
 |
 |      See Also
 |      --------
 |      Expr.dt.base_utc_offset : Base offset from UTC.
 |
 |      Examples
 |      --------
 |      >>> from datetime import datetime
 |      >>> df = pl.DataFrame(
 |      ...     {
 |      ...         "ts": [datetime(2020, 10, 25), datetime(2020, 10, 26)],
 |      ...     }
 |      ... )
 |      >>> df = df.with_columns(pl.col("ts").dt.replace_time_zone("Europe/London"))
 |      >>> df.with_columns(pl.col("ts").dt.dst_offset().alias("dst_offset"))
 |      shape: (2, 2)
 |      ┌─────────────────────────────┬──────────────┐
 |      │ ts                          ┆ dst_offset   │
 |      │ ---                         ┆ ---          │
 |      │ datetime[μs, Europe/London] ┆ duration[ms] │
 |      ╞═════════════════════════════╪══════════════╡
 |      │ 2020-10-25 00:00:00 BST     ┆ 1h           │
 |      │ 2020-10-26 00:00:00 GMT     ┆ 0ms          │
 |      └─────────────────────────────┴──────────────┘
 |
 |  epoch(self, time_unit: 'EpochTimeUnit' = 'us') -> 'Expr'
 |      Get the time passed since the Unix EPOCH in the give time unit.
 |
 |      Parameters
 |      ----------
 |      time_unit : {'ns', 'us', 'ms', 's', 'd'}
 |          Time unit.
 |
 |      Examples
 |      --------
 |      >>> from datetime import date
 |      >>> df = pl.date_range(
 |      ...     date(2001, 1, 1), date(2001, 1, 3), eager=True
 |      ... ).to_frame()
 |      >>> df.with_columns(
 |      ...     pl.col("date").dt.epoch().alias("epoch_ns"),
 |      ...     pl.col("date").dt.epoch(time_unit="s").alias("epoch_s"),
 |      ... )
 |      shape: (3, 3)
 |      ┌────────────┬─────────────────┬───────────┐
 |      │ date       ┆ epoch_ns        ┆ epoch_s   │
 |      │ ---        ┆ ---             ┆ ---       │
 |      │ date       ┆ i64             ┆ i64       │
 |      ╞════════════╪═════════════════╪═══════════╡
 |      │ 2001-01-01 ┆ 978307200000000 ┆ 978307200 │
 |      │ 2001-01-02 ┆ 978393600000000 ┆ 978393600 │
 |      │ 2001-01-03 ┆ 978480000000000 ┆ 978480000 │
 |      └────────────┴─────────────────┴───────────┘
 |
 |  hour(self) -> 'Expr'
 |      Extract hour from underlying DateTime representation.
 |
 |      Applies to Datetime columns.
 |
 |      Returns the hour number from 0 to 23.
 |
 |      Returns
 |      -------
 |      Expr
 |          Expression of data type :class:`Int8`.
 |
 |      Examples
 |      --------
 |      >>> from datetime import datetime
 |      >>> df = pl.DataFrame(
 |      ...     {
 |      ...         "datetime": [
 |      ...             datetime(2001, 1, 1, 0, 0, 0),
 |      ...             datetime(2010, 1, 1, 15, 30, 45),
 |      ...             datetime(2022, 12, 31, 23, 59, 59),
 |      ...         ]
 |      ...     }
 |      ... )
 |      >>> df.with_columns(pl.col("datetime").dt.hour().alias("hour"))
 |      shape: (3, 2)
 |      ┌─────────────────────┬──────┐
 |      │ datetime            ┆ hour │
 |      │ ---                 ┆ ---  │
 |      │ datetime[μs]        ┆ i8   │
 |      ╞═════════════════════╪══════╡
 |      │ 2001-01-01 00:00:00 ┆ 0    │
 |      │ 2010-01-01 15:30:45 ┆ 15   │
 |      │ 2022-12-31 23:59:59 ┆ 23   │
 |      └─────────────────────┴──────┘
 |
 |  hours(self) -> 'Expr'
 |      Extract the total hours from a Duration type.
 |
 |      .. deprecated:: 0.19.13
 |          Use :meth:`total_hours` instead.
 |
 |  is_leap_year(self) -> 'Expr'
 |      Determine whether the year of the underlying date is a leap year.
 |
 |      Applies to Date and Datetime columns.
 |
 |      Returns
 |      -------
 |      Expr
 |          Expression of data type :class:`Boolean`.
 |
 |      Examples
 |      --------
 |      >>> from datetime import date
 |      >>> df = pl.DataFrame(
 |      ...     {"date": [date(2000, 1, 1), date(2001, 1, 1), date(2002, 1, 1)]}
 |      ... )
 |      >>> df.select(pl.col("date").dt.is_leap_year())
 |      shape: (3, 1)
 |      ┌───────┐
 |      │ date  │
 |      │ ---   │
 |      │ bool  │
 |      ╞═══════╡
 |      │ true  │
 |      │ false │
 |      │ false │
 |      └───────┘
 |
 |  iso_year(self) -> 'Expr'
 |      Extract ISO year from underlying Date representation.
 |
 |      Applies to Date and Datetime columns.
 |
 |      Returns the year number in the ISO standard.
 |      This may not correspond with the calendar year.
 |
 |      Returns
 |      -------
 |      Expr
 |          Expression of data type :class:`Int32`.
 |
 |      Examples
 |      --------
 |      >>> from datetime import date
 |      >>> df = pl.DataFrame(
 |      ...     {"date": [date(1977, 1, 1), date(1978, 1, 1), date(1979, 1, 1)]}
 |      ... )
 |      >>> df.select(
 |      ...     "date",
 |      ...     pl.col("date").dt.year().alias("calendar_year"),
 |      ...     pl.col("date").dt.iso_year().alias("iso_year"),
 |      ... )
 |      shape: (3, 3)
 |      ┌────────────┬───────────────┬──────────┐
 |      │ date       ┆ calendar_year ┆ iso_year │
 |      │ ---        ┆ ---           ┆ ---      │
 |      │ date       ┆ i32           ┆ i32      │
 |      ╞════════════╪═══════════════╪══════════╡
 |      │ 1977-01-01 ┆ 1977          ┆ 1976     │
 |      │ 1978-01-01 ┆ 1978          ┆ 1977     │
 |      │ 1979-01-01 ┆ 1979          ┆ 1979     │
 |      └────────────┴───────────────┴──────────┘
 |
 |  microsecond(self) -> 'Expr'
 |      Extract microseconds from underlying DateTime representation.
 |
 |      Applies to Datetime columns.
 |
 |      Returns
 |      -------
 |      Expr
 |          Expression of data type :class:`Int32`.
 |
 |      Examples
 |      --------
 |      >>> from datetime import datetime
 |      >>> df = pl.DataFrame(
 |      ...     {
 |      ...         "date": pl.datetime_range(
 |      ...             datetime(2020, 1, 1),
 |      ...             datetime(2020, 1, 1, 0, 0, 1, 0),
 |      ...             "1ms",
 |      ...             eager=True,
 |      ...         ),
 |      ...     }
 |      ... )
 |      >>> df.select(
 |      ...     [
 |      ...         pl.col("date"),
 |      ...         pl.col("date").dt.microsecond().alias("microsecond"),
 |      ...     ]
 |      ... )
 |      shape: (1_001, 2)
 |      ┌─────────────────────────┬─────────────┐
 |      │ date                    ┆ microsecond │
 |      │ ---                     ┆ ---         │
 |      │ datetime[μs]            ┆ i32         │
 |      ╞═════════════════════════╪═════════════╡
 |      │ 2020-01-01 00:00:00     ┆ 0           │
 |      │ 2020-01-01 00:00:00.001 ┆ 1000        │
 |      │ 2020-01-01 00:00:00.002 ┆ 2000        │
 |      │ 2020-01-01 00:00:00.003 ┆ 3000        │
 |      │ …                       ┆ …           │
 |      │ 2020-01-01 00:00:00.997 ┆ 997000      │
 |      │ 2020-01-01 00:00:00.998 ┆ 998000      │
 |      │ 2020-01-01 00:00:00.999 ┆ 999000      │
 |      │ 2020-01-01 00:00:01     ┆ 0           │
 |      └─────────────────────────┴─────────────┘
 |
 |  microseconds(self) -> 'Expr'
 |      Extract the total microseconds from a Duration type.
 |
 |      .. deprecated:: 0.19.13
 |          Use :meth:`total_microseconds` instead.
 |
 |  millisecond(self) -> 'Expr'
 |      Extract milliseconds from underlying DateTime representation.
 |
 |      Applies to Datetime columns.
 |
 |      Returns
 |      -------
 |      Expr
 |          Expression of data type :class:`Int32`.
 |
 |  milliseconds(self) -> 'Expr'
 |      Extract the total milliseconds from a Duration type.
 |
 |      .. deprecated:: 0.19.13
 |          Use :meth:`total_milliseconds` instead.
 |
 |  minute(self) -> 'Expr'
 |      Extract minutes from underlying DateTime representation.
 |
 |      Applies to Datetime columns.
 |
 |      Returns the minute number from 0 to 59.
 |
 |      Returns
 |      -------
 |      Expr
 |          Expression of data type :class:`Int8`.
 |
 |      Examples
 |      --------
 |      >>> from datetime import datetime
 |      >>> df = pl.DataFrame(
 |      ...     {
 |      ...         "datetime": [
 |      ...             datetime(2001, 1, 1, 0, 0, 0),
 |      ...             datetime(2010, 1, 1, 15, 30, 45),
 |      ...             datetime(2022, 12, 31, 23, 59, 59),
 |      ...         ]
 |      ...     }
 |      ... )
 |      >>> df.with_columns(pl.col("datetime").dt.minute().alias("minute"))
 |      shape: (3, 2)
 |      ┌─────────────────────┬────────┐
 |      │ datetime            ┆ minute │
 |      │ ---                 ┆ ---    │
 |      │ datetime[μs]        ┆ i8     │
 |      ╞═════════════════════╪════════╡
 |      │ 2001-01-01 00:00:00 ┆ 0      │
 |      │ 2010-01-01 15:30:45 ┆ 30     │
 |      │ 2022-12-31 23:59:59 ┆ 59     │
 |      └─────────────────────┴────────┘
 |
 |  minutes(self) -> 'Expr'
 |      Extract the total minutes from a Duration type.
 |
 |      .. deprecated:: 0.19.13
 |          Use :meth:`total_minutes` instead.
 |
 |  month(self) -> 'Expr'
 |      Extract month from underlying Date representation.
 |
 |      Applies to Date and Datetime columns.
 |
 |      Returns the month number starting from 1.
 |      The return value ranges from 1 to 12.
 |
 |      Returns
 |      -------
 |      Expr
 |          Expression of data type :class:`Int8`.
 |
 |      Examples
 |      --------
 |      >>> from datetime import date
 |      >>> df = pl.DataFrame(
 |      ...     {"date": [date(2001, 1, 1), date(2001, 6, 30), date(2001, 12, 27)]}
 |      ... )
 |      >>> df.with_columns(pl.col("date").dt.month().alias("month"))
 |      shape: (3, 2)
 |      ┌────────────┬───────┐
 |      │ date       ┆ month │
 |      │ ---        ┆ ---   │
 |      │ date       ┆ i8    │
 |      ╞════════════╪═══════╡
 |      │ 2001-01-01 ┆ 1     │
 |      │ 2001-06-30 ┆ 6     │
 |      │ 2001-12-27 ┆ 12    │
 |      └────────────┴───────┘
 |
 |  month_end(self) -> 'Expr'
 |      Roll forward to the last day of the month.
 |
 |      Returns
 |      -------
 |      Expr
 |          Expression of data type :class:`Date` or :class:`Datetime`.
 |
 |      Notes
 |      -----
 |      If you're coming from pandas, you can think of this as a vectorised version
 |      of `pandas.tseries.offsets.MonthEnd().rollforward(datetime)`.
 |
 |      Examples
 |      --------
 |      >>> from datetime import datetime
 |      >>> df = pl.DataFrame(
 |      ...     {

In [83]:
help(pl.col('bio').str)

Help on ExprStringNameSpace in module polars.expr.string object:

class ExprStringNameSpace(builtins.object)
 |  ExprStringNameSpace(expr: 'Expr')
 |
 |  Namespace for string related expressions.
 |
 |  Methods defined here:
 |
 |  __init__(self, expr: 'Expr')
 |      Initialize self.  See help(type(self)) for accurate signature.
 |
 |  concat(self, delimiter: 'str' = '-', *, ignore_nulls: 'bool' = True) -> 'Expr'
 |      Vertically concat the values in the Series to a single string value.
 |
 |      Parameters
 |      ----------
 |      delimiter
 |          The delimiter to insert between consecutive string values.
 |      ignore_nulls
 |          Ignore null values (default).
 |
 |          If set to ``False``, null values will be propagated.
 |          if the column contains any null values, the output is ``None``.
 |
 |      Returns
 |      -------
 |      Expr
 |          Expression of data type :class:`Utf8`.
 |
 |      Examples
 |      --------
 |      >>> df = pl.DataFrame({"foo": [1, None, 2]})
 |      >>> df.select(pl.col("foo").str.concat("-"))
 |      shape: (1, 1)
 |      ┌─────┐
 |      │ foo │
 |      │ --- │
 |      │ str │
 |      ╞═════╡
 |      │ 1-2 │
 |      └─────┘
 |      >>> df = pl.DataFrame({"foo": [1, None, 2]})
 |      >>> df.select(pl.col("foo").str.concat("-", ignore_nulls=False))
 |      shape: (1, 1)
 |      ┌──────┐
 |      │ foo  │
 |      │ ---  │
 |      │ str  │
 |      ╞══════╡
 |      │ null │
 |      └──────┘
 |
 |  contains(self, pattern: 'str | Expr', *, literal: 'bool' = False, strict: 'bool' = True) -> 'Expr'
 |      Check if string contains a substring that matches a regex.
 |
 |      Parameters
 |      ----------
 |      pattern
 |          A valid regular expression pattern, compatible with the `regex crate
 |          <https://docs.rs/regex/latest/regex/>`_.
 |      literal
 |          Treat `pattern` as a literal string, not as a regular expression.
 |      strict
 |          Raise an error if the underlying pattern is not a valid regex,
 |          otherwise mask out with a null value.
 |
 |      Notes
 |      -----
 |      To modify regular expression behaviour (such as case-sensitivity) with
 |      flags, use the inline `(?iLmsuxU)` syntax. For example:
 |
 |      >>> pl.DataFrame({"s": ["AAA", "aAa", "aaa"]}).with_columns(
 |      ...     default_match=pl.col("s").str.contains("AA"),
 |      ...     insensitive_match=pl.col("s").str.contains("(?i)AA"),
 |      ... )
 |      shape: (3, 3)
 |      ┌─────┬───────────────┬───────────────────┐
 |      │ s   ┆ default_match ┆ insensitive_match │
 |      │ --- ┆ ---           ┆ ---               │
 |      │ str ┆ bool          ┆ bool              │
 |      ╞═════╪═══════════════╪═══════════════════╡
 |      │ AAA ┆ true          ┆ true              │
 |      │ aAa ┆ false         ┆ true              │
 |      │ aaa ┆ false         ┆ true              │
 |      └─────┴───────────────┴───────────────────┘
 |
 |      See the regex crate's section on `grouping and flags
 |      <https://docs.rs/regex/latest/regex/#grouping-and-flags>`_ for
 |      additional information about the use of inline expression modifiers.
 |
 |      See Also
 |      --------
 |      starts_with : Check if string values start with a substring.
 |      ends_with : Check if string values end with a substring.
 |
 |      Examples
 |      --------
 |      >>> df = pl.DataFrame({"a": ["Crab", "cat and dog", "rab$bit", None]})
 |      >>> df.select(
 |      ...     pl.col("a"),
 |      ...     pl.col("a").str.contains("cat|bit").alias("regex"),
 |      ...     pl.col("a").str.contains("rab$", literal=True).alias("literal"),
 |      ... )
 |      shape: (4, 3)
 |      ┌─────────────┬───────┬─────────┐
 |      │ a           ┆ regex ┆ literal │
 |      │ ---         ┆ ---   ┆ ---     │
 |      │ str         ┆ bool  ┆ bool    │
 |      ╞═════════════╪═══════╪═════════╡
 |      │ Crab        ┆ false ┆ false   │
 |      │ cat and dog ┆ true  ┆ false   │
 |      │ rab$bit     ┆ true  ┆ true    │
 |      │ null        ┆ null  ┆ null    │
 |      └─────────────┴───────┴─────────┘
 |
 |  contains_any(self, patterns: 'IntoExpr', *, ascii_case_insensitive: 'bool' = False) -> 'Expr'
 |      Use the aho-corasick algorithm to find matches.
 |
 |      This version determines if any of the patterns find a match.
 |
 |      Parameters
 |      ----------
 |      patterns
 |          String patterns to search.
 |      ascii_case_insensitive
 |          Enable ASCII-aware case insensitive matching.
 |          When this option is enabled, searching will be performed without respect
 |          to case for ASCII letters (a-z and A-Z) only.
 |
 |      Examples
 |      --------
 |      >>> _ = pl.Config.set_fmt_str_lengths(100)
 |      >>> df = pl.DataFrame(
 |      ...     {
 |      ...         "lyrics": [
 |      ...             "Everybody wants to rule the world",
 |      ...             "Tell me what you want, what you really really want",
 |      ...             "Can you feel the love tonight",
 |      ...         ]
 |      ...     }
 |      ... )
 |      >>> df.with_columns(
 |      ...     pl.col("lyrics").str.contains_any(["you", "me"]).alias("contains_any")
 |      ... )
 |      shape: (3, 2)
 |      ┌────────────────────────────────────────────────────┬──────────────┐
 |      │ lyrics                                             ┆ contains_any │
 |      │ ---                                                ┆ ---          │
 |      │ str                                                ┆ bool         │
 |      ╞════════════════════════════════════════════════════╪══════════════╡
 |      │ Everybody wants to rule the world                  ┆ false        │
 |      │ Tell me what you want, what you really really want ┆ true         │
 |      │ Can you feel the love tonight                      ┆ true         │
 |      └────────────────────────────────────────────────────┴──────────────┘
 |
 |  count_match(self, pattern: 'str | Expr') -> 'Expr'
 |      Count all successive non-overlapping regex matches.
 |
 |      .. deprecated:: 0.19.3
 |          This method has been renamed to :func:`count_matches`.
 |
 |      Parameters
 |      ----------
 |      pattern
 |          A valid regular expression pattern, compatible with the `regex crate
 |          <https://docs.rs/regex/latest/regex/>`_.
 |
 |      Returns
 |      -------
 |      Expr
 |          Expression of data type :class:`UInt32`. Returns null if the
 |          original value is null.
 |
 |  count_matches(self, pattern: 'str | Expr', *, literal: 'bool' = False) -> 'Expr'
 |      Count all successive non-overlapping regex matches.
 |
 |      Parameters
 |      ----------
 |      pattern
 |          A valid regular expression pattern, compatible with the `regex crate
 |          <https://docs.rs/regex/latest/regex/>`_.
 |      literal
 |          Treat `pattern` as a literal string, not as a regular expression.
 |
 |      Returns
 |      -------
 |      Expr
 |          Expression of data type :class:`UInt32`. Returns null if the
 |          original value is null.
 |
 |      Examples
 |      --------
 |      >>> df = pl.DataFrame({"foo": ["123 bla 45 asd", "xyz 678 910t", "bar", None]})
 |      >>> df.with_columns(
 |      ...     pl.col("foo").str.count_matches(r"\d").alias("count_digits"),
 |      ... )
 |      shape: (4, 2)
 |      ┌────────────────┬──────────────┐
 |      │ foo            ┆ count_digits │
 |      │ ---            ┆ ---          │
 |      │ str            ┆ u32          │
 |      ╞════════════════╪══════════════╡
 |      │ 123 bla 45 asd ┆ 5            │
 |      │ xyz 678 910t   ┆ 6            │
 |      │ bar            ┆ 0            │
 |      │ null           ┆ null         │
 |      └────────────────┴──────────────┘
 |
 |      >>> df = pl.DataFrame({"bar": ["12 dbc 3xy", "cat\\w", "1zy3\\d\\d", None]})
 |      >>> df.with_columns(
 |      ...     pl.col("bar")
 |      ...     .str.count_matches(r"\d", literal=True)
 |      ...     .alias("count_digits"),
 |      ... )
 |      shape: (4, 2)
 |      ┌────────────┬──────────────┐
 |      │ bar        ┆ count_digits │
 |      │ ---        ┆ ---          │
 |      │ str        ┆ u32          │
 |      ╞════════════╪══════════════╡
 |      │ 12 dbc 3xy ┆ 0            │
 |      │ cat\w      ┆ 0            │
 |      │ 1zy3\d\d   ┆ 2            │
 |      │ null       ┆ null         │
 |      └────────────┴──────────────┘
 |
 |  decode(self, encoding: 'TransferEncoding', *, strict: 'bool' = True) -> 'Expr'
 |      Decode a value using the provided encoding.
 |
 |      Parameters
 |      ----------
 |      encoding : {'hex', 'base64'}
 |          The encoding to use.
 |      strict
 |          Raise an error if the underlying value cannot be decoded,
 |          otherwise mask out with a null value.
 |
 |  encode(self, encoding: 'TransferEncoding') -> 'Expr'
 |      Encode a value using the provided encoding.
 |
 |      Parameters
 |      ----------
 |      encoding : {'hex', 'base64'}
 |          The encoding to use.
 |
 |      Returns
 |      -------
 |      Expr
 |          Expression of data type :class:`Utf8`.
 |
 |      Examples
 |      --------
 |      >>> df = pl.DataFrame({"strings": ["foo", "bar", None]})
 |      >>> df.with_columns(strings_hex=pl.col("strings").str.encode("hex"))
 |      shape: (3, 2)
 |      ┌─────────┬─────────────┐
 |      │ strings ┆ strings_hex │
 |      │ ---     ┆ ---         │
 |      │ str     ┆ str         │
 |      ╞═════════╪═════════════╡
 |      │ foo     ┆ 666f6f      │
 |      │ bar     ┆ 626172      │
 |      │ null    ┆ null        │
 |      └─────────┴─────────────┘
 |
 |  ends_with(self, suffix: 'str | Expr') -> 'Expr'
 |      Check if string values end with a substring.
 |
 |      Parameters
 |      ----------
 |      suffix
 |          Suffix substring.
 |
 |      See Also
 |      --------
 |      contains : Check if string contains a substring that matches a regex.
 |      starts_with : Check if string values start with a substring.
 |
 |      Examples
 |      --------
 |      >>> df = pl.DataFrame({"fruits": ["apple", "mango", None]})
 |      >>> df.with_columns(
 |      ...     pl.col("fruits").str.ends_with("go").alias("has_suffix"),
 |      ... )
 |      shape: (3, 2)
 |      ┌────────┬────────────┐
 |      │ fruits ┆ has_suffix │
 |      │ ---    ┆ ---        │
 |      │ str    ┆ bool       │
 |      ╞════════╪════════════╡
 |      │ apple  ┆ false      │
 |      │ mango  ┆ true       │
 |      │ null   ┆ null       │
 |      └────────┴────────────┘
 |
 |      >>> df = pl.DataFrame(
 |      ...     {"fruits": ["apple", "mango", "banana"], "suffix": ["le", "go", "nu"]}
 |      ... )
 |      >>> df.with_columns(
 |      ...     pl.col("fruits").str.ends_with(pl.col("suffix")).alias("has_suffix"),
 |      ... )
 |      shape: (3, 3)
 |      ┌────────┬────────┬────────────┐
 |      │ fruits ┆ suffix ┆ has_suffix │
 |      │ ---    ┆ ---    ┆ ---        │
 |      │ str    ┆ str    ┆ bool       │
 |      ╞════════╪════════╪════════════╡
 |      │ apple  ┆ le     ┆ true       │
 |      │ mango  ┆ go     ┆ true       │
 |      │ banana ┆ nu     ┆ false      │
 |      └────────┴────────┴────────────┘
 |
 |      Using `ends_with` as a filter condition:
 |
 |      >>> df.filter(pl.col("fruits").str.ends_with("go"))
 |      shape: (1, 2)
 |      ┌────────┬────────┐
 |      │ fruits ┆ suffix │
 |      │ ---    ┆ ---    │
 |      │ str    ┆ str    │
 |      ╞════════╪════════╡
 |      │ mango  ┆ go     │
 |      └────────┴────────┘
 |
 |  explode(self) -> 'Expr'
 |      Returns a column with a separate row for every string character.
 |
 |      Returns
 |      -------
 |      Expr
 |          Expression of data type :class:`Utf8`.
 |
 |      Examples
 |      --------
 |      >>> df = pl.DataFrame({"a": ["foo", "bar"]})
 |      >>> df.select(pl.col("a").str.explode())
 |      shape: (6, 1)
 |      ┌─────┐
 |      │ a   │
 |      │ --- │
 |      │ str │
 |      ╞═════╡
 |      │ f   │
 |      │ o   │
 |      │ o   │
 |      │ b   │
 |      │ a   │
 |      │ r   │
 |      └─────┘
 |
 |  extract(self, pattern: 'str', group_index: 'int' = 1) -> 'Expr'
 |      Extract the target capture group from provided patterns.
 |
 |      Parameters
 |      ----------
 |      pattern
 |          A valid regular expression pattern, compatible with the `regex crate
 |          <https://docs.rs/regex/latest/regex/>`_.
 |      group_index
 |          Index of the targeted capture group.
 |          Group 0 means the whole pattern, the first group begins at index 1.
 |          Defaults to the first capture group.
 |
 |      Notes
 |      -----
 |      To modify regular expression behaviour (such as multi-line matching)
 |      with flags, use the inline `(?iLmsuxU)` syntax. For example:
 |
 |      >>> df = pl.DataFrame(
 |      ...     data={
 |      ...         "lines": [
 |      ...             "I Like\nThose\nOdds",
 |      ...             "This is\nThe Way",
 |      ...         ]
 |      ...     }
 |      ... )
 |      >>> df.with_columns(
 |      ...     pl.col("lines").str.extract(r"(?m)^(T\w+)", 1).alias("matches"),
 |      ... )
 |      shape: (2, 2)
 |      ┌─────────┬─────────┐
 |      │ lines   ┆ matches │
 |      │ ---     ┆ ---     │
 |      │ str     ┆ str     │
 |      ╞═════════╪═════════╡
 |      │ I Like  ┆ Those   │
 |      │ Those   ┆         │
 |      │ Odds    ┆         │
 |      │ This is ┆ This    │
 |      │ The Way ┆         │
 |      └─────────┴─────────┘
 |
 |      See the regex crate's section on `grouping and flags
 |      <https://docs.rs/regex/latest/regex/#grouping-and-flags>`_ for
 |      additional information about the use of inline expression modifiers.
 |
 |      Returns
 |      -------
 |      Expr
 |          Expression of data type :class:`Utf8`. Contains null values if original
 |          value is null or the regex captures nothing.
 |
 |      Examples
 |      --------
 |      >>> df = pl.DataFrame(
 |      ...     {
 |      ...         "url": [
 |      ...             "http://vote.com/ballon_dor?error=404&ref=unknown",
 |      ...             "http://vote.com/ballon_dor?ref=polars&candidate=messi",
 |      ...             "http://vote.com/ballon_dor?candidate=ronaldo&ref=polars",
 |      ...         ]
 |      ...     }
 |      ... )
 |      >>> df.select(
 |      ...     pl.col("url").str.extract(r"candidate=(\w+)", 1).alias("candidate"),
 |      ...     pl.col("url").str.extract(r"ref=(\w+)", 1).alias("referer"),
 |      ...     pl.col("url").str.extract(r"error=(\w+)", 1).alias("error"),
 |      ... )
 |      shape: (3, 3)
 |      ┌───────────┬─────────┬───────┐
 |      │ candidate ┆ referer ┆ error │
 |      │ ---       ┆ ---     ┆ ---   │
 |      │ str       ┆ str     ┆ str   │
 |      ╞═══════════╪═════════╪═══════╡
 |      │ null      ┆ unknown ┆ 404   │
 |      │ messi     ┆ polars  ┆ null  │
 |      │ ronaldo   ┆ polars  ┆ null  │
 |      └───────────┴─────────┴───────┘
 |
 |  extract_all(self, pattern: 'str | Expr') -> 'Expr'
 |      Extract all matches for the given regex pattern.
 |
 |      Extract each successive non-overlapping regex match in an individual string
 |      as a list. If the haystack string is `null`, `null` is returned.
 |
 |      Parameters
 |      ----------
 |      pattern
 |          A valid regular expression pattern, compatible with the `regex crate
 |          <https://docs.rs/regex/latest/regex/>`_.
 |
 |      Notes
 |      -----
 |      To modify regular expression behaviour (such as "verbose" mode and/or
 |      case-sensitive matching) with flags, use the inline `(?iLmsuxU)` syntax.
 |      For example:
 |
 |      >>> df = pl.DataFrame(
 |      ...     data={
 |      ...         "email": [
 |      ...             "real.email@spam.com",
 |      ...             "some_account@somewhere.net",
 |      ...             "abc.def.ghi.jkl@uvw.xyz.co.uk",
 |      ...         ]
 |      ...     }
 |      ... )
 |      >>> # extract name/domain parts from the addresses, using verbose regex
 |      >>> df.with_columns(
 |      ...     pl.col("email")
 |      ...     .str.extract_all(
 |      ...         r"""(?xi)   # activate 'verbose' and 'case-insensitive' flags
 |      ...         [           # (start character group)
 |      ...           A-Z       # letters
 |      ...           0-9       # digits
 |      ...           ._%+\-    # special chars
 |      ...         ]           # (end character group)
 |      ...         +           # 'one or more' quantifier
 |      ...         """
 |      ...     )
 |      ...     .list.to_struct(fields=["name", "domain"])
 |      ...     .alias("email_parts")
 |      ... ).unnest("email_parts")
 |      shape: (3, 3)
 |      ┌───────────────────────────────┬─────────────────┬───────────────┐
 |      │ email                         ┆ name            ┆ domain        │
 |      │ ---                           ┆ ---             ┆ ---           │
 |      │ str                           ┆ str             ┆ str           │
 |      ╞═══════════════════════════════╪═════════════════╪═══════════════╡
 |      │ real.email@spam.com           ┆ real.email      ┆ spam.com      │
 |      │ some_account@somewhere.net    ┆ some_account    ┆ somewhere.net │
 |      │ abc.def.ghi.jkl@uvw.xyz.co.uk ┆ abc.def.ghi.jkl ┆ uvw.xyz.co.uk │
 |      └───────────────────────────────┴─────────────────┴───────────────┘
 |
 |      See the regex crate's section on `grouping and flags
 |      <https://docs.rs/regex/latest/regex/#grouping-and-flags>`_ for
 |      additional information about the use of inline expression modifiers.
 |
 |      Returns
 |      -------
 |      Expr
 |          Expression of data type `List(Utf8)`.
 |
 |      Examples
 |      --------
 |      >>> df = pl.DataFrame({"foo": ["123 bla 45 asd", "xyz 678 910t", "bar", None]})
 |      >>> df.select(
 |      ...     pl.col("foo").str.extract_all(r"\d+").alias("extracted_nrs"),
 |      ... )
 |      shape: (4, 1)
 |      ┌────────────────┐
 |      │ extracted_nrs  │
 |      │ ---            │
 |      │ list[str]      │
 |      ╞════════════════╡
 |      │ ["123", "45"]  │
 |      │ ["678", "910"] │
 |      │ []             │
 |      │ null           │
 |      └────────────────┘
 |
 |  extract_groups(self, pattern: 'str') -> 'Expr'
 |      Extract all capture groups for the given regex pattern.
 |
 |      Parameters
 |      ----------
 |      pattern
 |          A valid regular expression pattern, compatible with the `regex crate
 |          <https://docs.rs/regex/latest/regex/>`_.
 |
 |      Notes
 |      -----
 |      All group names are **strings**.
 |
 |      If your pattern contains unnamed groups, their numerical position is converted
 |      to a string.
 |
 |      For example, here we access groups 2 and 3 via the names `"2"` and `"3"`::
 |
 |          >>> df = pl.DataFrame({"col": ["foo bar baz"]})
 |          >>> (
 |          ...     df.with_columns(
 |          ...         pl.col("col").str.extract_groups(r"(\S+) (\S+) (.+)")
 |          ...     ).select(pl.col("col").struct["2"], pl.col("col").struct["3"])
 |          ... )
 |          shape: (1, 2)
 |          ┌─────┬─────┐
 |          │ 2   ┆ 3   │
 |          │ --- ┆ --- │
 |          │ str ┆ str │
 |          ╞═════╪═════╡
 |          │ bar ┆ baz │
 |          └─────┴─────┘
 |
 |      Returns
 |      -------
 |      Expr
 |          Expression of data type :class:`Struct` with fields of data type
 |          :class:`Utf8`.
 |
 |      Examples
 |      --------
 |      >>> df = pl.DataFrame(
 |      ...     data={
 |      ...         "url": [
 |      ...             "http://vote.com/ballon_dor?candidate=messi&ref=python",
 |      ...             "http://vote.com/ballon_dor?candidate=weghorst&ref=polars",
 |      ...             "http://vote.com/ballon_dor?error=404&ref=rust",
 |      ...         ]
 |      ...     }
 |      ... )
 |      >>> pattern = r"candidate=(?<candidate>\w+)&ref=(?<ref>\w+)"

In [82]:
df.select(
    pl.col('bio').str.len
)

AttributeError: 'ExprStringNameSpace' object has no attribute 'len'

In [86]:
df.filter(pl.col('birthday')>datetime(2000, 1, 1))

shape: (3, 5)
┌─────┬──────┬─────────────────────┬────────┬────────────────────┐
│ idx ┆ name ┆ birthday            ┆ gender ┆ bio                │
│ --- ┆ ---  ┆ ---                 ┆ ---    ┆ ---                │
│ i64 ┆ str  ┆ datetime[μs]        ┆ str    ┆ str                │
╞═════╪══════╪═════════════════════╪════════╪════════════════════╡
│ 1   ┆ 张三 ┆ 2009-05-01 00:00:00 ┆ 男     ┆ 好好学习，天天向上 │
│ 2   ┆ 李四 ┆ 2005-10-15 00:00:00 ┆ 男     ┆ 泰难了             │
│ 3   ┆ 王五 ┆ 2000-12-31 00:00:00 ┆ 男     ┆ 学习有毛用         │
└─────┴──────┴─────────────────────┴────────┴────────────────────┘

In [87]:
df.filter(
  pl.col('bio').str.contains("学习")
)

shape: (2, 5)
┌─────┬──────┬─────────────────────┬────────┬────────────────────┐
│ idx ┆ name ┆ birthday            ┆ gender ┆ bio                │
│ --- ┆ ---  ┆ ---                 ┆ ---    ┆ ---                │
│ i64 ┆ str  ┆ datetime[μs]        ┆ str    ┆ str                │
╞═════╪══════╪═════════════════════╪════════╪════════════════════╡
│ 1   ┆ 张三 ┆ 2009-05-01 00:00:00 ┆ 男     ┆ 好好学习，天天向上 │
│ 3   ┆ 王五 ┆ 2000-12-31 00:00:00 ┆ 男     ┆ 学习有毛用         │
└─────┴──────┴─────────────────────┴────────┴────────────────────┘

In [88]:
df.groupby('gender')

/var/folders/y0/4gqxky0s2t94x1c1qhlwr6100000gn/T/ipykernel_61402/3772552469.py:1: DeprecationWarning: `groupby` is deprecated. It has been renamed to `group_by`.
  df.groupby('gender')

In [91]:
for gender, gender_df in df.groupby(pl.col('gender')):
    print(gender, len(gender_df), type(gender_df))

男 3 <class 'polars.dataframe.frame.DataFrame'>
女 1 <class 'polars.dataframe.frame.DataFrame'>

/var/folders/y0/4gqxky0s2t94x1c1qhlwr6100000gn/T/ipykernel_61402/662584614.py:1: DeprecationWarning: `groupby` is deprecated. It has been renamed to `group_by`.
  for gender, gender_df in df.groupby(pl.col('gender')):

In [97]:
for gender, gender_df in df.groupby(pl.col('gender')):
    print(gender,  gender_df['bio'].apply(lambda t: len(t)).mean())

男 5.666666666666667
女 5.0

/var/folders/y0/4gqxky0s2t94x1c1qhlwr6100000gn/T/ipykernel_61402/4178240173.py:1: DeprecationWarning: `groupby` is deprecated. It has been renamed to `group_by`.
  for gender, gender_df in df.groupby(pl.col('gender')):
/var/folders/y0/4gqxky0s2t94x1c1qhlwr6100000gn/T/ipykernel_61402/4178240173.py:2: DeprecationWarning: `apply` is deprecated. It has been renamed to `map_elements`.
  print(gender,  gender_df['bio'].apply(lambda t: len(t)).mean())

In [105]:
df.groupby(pl.col('gender')).agg(pl.col('bio').apply(lambda t: len(t)))

/var/folders/y0/4gqxky0s2t94x1c1qhlwr6100000gn/T/ipykernel_61402/2837407314.py:1: DeprecationWarning: `groupby` is deprecated. It has been renamed to `group_by`.
  df.groupby(pl.col('gender')).agg(pl.col('bio').apply(lambda t: len(t)))
/var/folders/y0/4gqxky0s2t94x1c1qhlwr6100000gn/T/ipykernel_61402/2837407314.py:1: DeprecationWarning: `apply` is deprecated. It has been renamed to `map_elements`.
  df.groupby(pl.col('gender')).agg(pl.col('bio').apply(lambda t: len(t)))

shape: (2, 2)
┌────────┬─────┐
│ gender ┆ bio │
│ ---    ┆ --- │
│ str    ┆ i64 │
╞════════╪═════╡
│ 女     ┆ 1   │
│ 男     ┆ 3   │
└────────┴─────┘

In [119]:
df

shape: (4, 5)
┌─────┬──────┬─────────────────────┬────────┬────────────────────┐
│ idx ┆ name ┆ birthday            ┆ gender ┆ bio                │
│ --- ┆ ---  ┆ ---                 ┆ ---    ┆ ---                │
│ i64 ┆ str  ┆ datetime[μs]        ┆ str    ┆ str                │
╞═════╪══════╪═════════════════════╪════════╪════════════════════╡
│ 1   ┆ 张三 ┆ 2009-05-01 00:00:00 ┆ 男     ┆ 好好学习，天天向上 │
│ 2   ┆ 李四 ┆ 2005-10-15 00:00:00 ┆ 男     ┆ 泰难了             │
│ 3   ┆ 王五 ┆ 2000-12-31 00:00:00 ┆ 男     ┆ 学习有毛用         │
│ 4   ┆ 赵六 ┆ 1995-06-15 00:00:00 ┆ 女     ┆ 躺平ing            │
└─────┴──────┴─────────────────────┴────────┴────────────────────┘

In [121]:
import polars.selectors as cs

df.select(
    cs.integer(), cs.string()
)

shape: (4, 4)
┌─────┬──────┬────────┬────────────────────┐
│ idx ┆ name ┆ gender ┆ bio                │
│ --- ┆ ---  ┆ ---    ┆ ---                │
│ i64 ┆ str  ┆ str    ┆ str                │
╞═════╪══════╪════════╪════════════════════╡
│ 1   ┆ 张三 ┆ 男     ┆ 好好学习，天天向上 │
│ 2   ┆ 李四 ┆ 男     ┆ 泰难了             │
│ 3   ┆ 王五 ┆ 男     ┆ 学习有毛用         │
│ 4   ┆ 赵六 ┆ 女     ┆ 躺平ing            │
└─────┴──────┴────────┴────────────────────┘

In [124]:
df.select(
    cs.contains('r')
)

shape: (4, 2)
┌─────────────────────┬────────┐
│ birthday            ┆ gender │
│ ---                 ┆ ---    │
│ datetime[μs]        ┆ str    │
╞═════════════════════╪════════╡
│ 2009-05-01 00:00:00 ┆ 男     │
│ 2005-10-15 00:00:00 ┆ 男     │
│ 2000-12-31 00:00:00 ┆ 男     │
│ 1995-06-15 00:00:00 ┆ 女     │
└─────────────────────┴────────┘

In [130]:
#筛选出字段名含 r 的字段
df.select(
    cs.datetime().dt.to_string("%Y-%M-%d")
)

shape: (4, 1)
┌────────────┐
│ birthday   │
│ ---        │
│ str        │
╞════════════╡
│ 2009-00-01 │
│ 2005-00-15 │
│ 2000-00-31 │
│ 1995-00-15 │
└────────────┘

In [134]:
#筛选出字段名含 r 的字段
df.select(
    cs.temporal()
)

shape: (4, 1)
┌─────────────────────┐
│ birthday            │
│ ---                 │
│ datetime[μs]        │
╞═════════════════════╡
│ 2009-05-01 00:00:00 │
│ 2005-10-15 00:00:00 │
│ 2000-12-31 00:00:00 │
│ 1995-06-15 00:00:00 │
└─────────────────────┘

In [132]:
df

shape: (4, 5)
┌─────┬──────┬─────────────────────┬────────┬────────────────────┐
│ idx ┆ name ┆ birthday            ┆ gender ┆ bio                │
│ --- ┆ ---  ┆ ---                 ┆ ---    ┆ ---                │
│ i64 ┆ str  ┆ datetime[μs]        ┆ str    ┆ str                │
╞═════╪══════╪═════════════════════╪════════╪════════════════════╡
│ 1   ┆ 张三 ┆ 2009-05-01 00:00:00 ┆ 男     ┆ 好好学习，天天向上 │
│ 2   ┆ 李四 ┆ 2005-10-15 00:00:00 ┆ 男     ┆ 泰难了             │
│ 3   ┆ 王五 ┆ 2000-12-31 00:00:00 ┆ 男     ┆ 学习有毛用         │
│ 4   ┆ 赵六 ┆ 1995-06-15 00:00:00 ┆ 女     ┆ 躺平ing            │
└─────┴──────┴─────────────────────┴────────┴────────────────────┘

In [133]:
df.select(
    cs.matches('na|io')
)

shape: (4, 2)
┌──────┬────────────────────┐
│ name ┆ bio                │
│ ---  ┆ ---                │
│ str  ┆ str                │
╞══════╪════════════════════╡
│ 张三 ┆ 好好学习，天天向上 │
│ 李四 ┆ 泰难了             │
│ 王五 ┆ 学习有毛用         │
│ 赵六 ┆ 躺平ing            │
└──────┴────────────────────┘

In [136]:
df.with_columns(
    pl.when(pl.col('birthday')>datetime(2000, 1, 1))
    .then(True)
    .otherwise(False)
    .alias('00后')
)

shape: (4, 6)
┌─────┬──────┬─────────────────────┬────────┬────────────────────┬───────┐
│ idx ┆ name ┆ birthday            ┆ gender ┆ bio                ┆ 00后  │
│ --- ┆ ---  ┆ ---                 ┆ ---    ┆ ---                ┆ ---   │
│ i64 ┆ str  ┆ datetime[μs]        ┆ str    ┆ str                ┆ bool  │
╞═════╪══════╪═════════════════════╪════════╪════════════════════╪═══════╡
│ 1   ┆ 张三 ┆ 2009-05-01 00:00:00 ┆ 男     ┆ 好好学习，天天向上 ┆ true  │
│ 2   ┆ 李四 ┆ 2005-10-15 00:00:00 ┆ 男     ┆ 泰难了             ┆ true  │
│ 3   ┆ 王五 ┆ 2000-12-31 00:00:00 ┆ 男     ┆ 学习有毛用         ┆ true  │
│ 4   ┆ 赵六 ┆ 1995-06-15 00:00:00 ┆ 女     ┆ 躺平ing            ┆ false │
└─────┴──────┴─────────────────────┴────────┴────────────────────┴───────┘

In [153]:
df.with_columns(
    pl.col('bio').str.len_chars().alias('lenth')
)

shape: (4, 6)
┌─────┬──────┬─────────────────────┬────────┬────────────────────┬───────┐
│ idx ┆ name ┆ birthday            ┆ gender ┆ bio                ┆ lenth │
│ --- ┆ ---  ┆ ---                 ┆ ---    ┆ ---                ┆ ---   │
│ i64 ┆ str  ┆ datetime[μs]        ┆ str    ┆ str                ┆ u32   │
╞═════╪══════╪═════════════════════╪════════╪════════════════════╪═══════╡
│ 1   ┆ 张三 ┆ 2009-05-01 00:00:00 ┆ 男     ┆ 好好学习，天天向上 ┆ 9     │
│ 2   ┆ 李四 ┆ 2005-10-15 00:00:00 ┆ 男     ┆ 泰难了             ┆ 3     │
│ 3   ┆ 王五 ┆ 2000-12-31 00:00:00 ┆ 男     ┆ 学习有毛用         ┆ 5     │
│ 4   ┆ 赵六 ┆ 1995-06-15 00:00:00 ┆ 女     ┆ 躺平ing            ┆ 5     │
└─────┴──────┴─────────────────────┴────────┴────────────────────┴───────┘

In [156]:
df.with_columns(
    pl.col('bio').str.extract_all('躺平|难|毛').alias('neg')
)

shape: (4, 6)
┌─────┬──────┬─────────────────────┬────────┬────────────────────┬───────────┐
│ idx ┆ name ┆ birthday            ┆ gender ┆ bio                ┆ neg       │
│ --- ┆ ---  ┆ ---                 ┆ ---    ┆ ---                ┆ ---       │
│ i64 ┆ str  ┆ datetime[μs]        ┆ str    ┆ str                ┆ list[str] │
╞═════╪══════╪═════════════════════╪════════╪════════════════════╪═══════════╡
│ 1   ┆ 张三 ┆ 2009-05-01 00:00:00 ┆ 男     ┆ 好好学习，天天向上 ┆ []        │
│ 2   ┆ 李四 ┆ 2005-10-15 00:00:00 ┆ 男     ┆ 泰难了             ┆ ["难"]    │
│ 3   ┆ 王五 ┆ 2000-12-31 00:00:00 ┆ 男     ┆ 学习有毛用         ┆ ["毛"]    │
│ 4   ┆ 赵六 ┆ 1995-06-15 00:00:00 ┆ 女     ┆ 躺平ing            ┆ ["躺平"]  │
└─────┴──────┴─────────────────────┴────────┴────────────────────┴───────────┘

In [148]:
help(pl.col('bio').str.extract)

Help on method extract in module polars.expr.string:

extract(pattern: 'str', group_index: 'int' = 1) -> 'Expr' method of polars.expr.string.ExprStringNameSpace instance
    Extract the target capture group from provided patterns.

    Parameters
    ----------
    pattern
        A valid regular expression pattern, compatible with the `regex crate
        <https://docs.rs/regex/latest/regex/>`_.
    group_index
        Index of the targeted capture group.
        Group 0 means the whole pattern, the first group begins at index 1.
        Defaults to the first capture group.

    Notes
    -----
    To modify regular expression behaviour (such as multi-line matching)
    with flags, use the inline `(?iLmsuxU)` syntax. For example:

    >>> df = pl.DataFrame(
    ...     data={
    ...         "lines": [
    ...             "I Like\nThose\nOdds",
    ...             "This is\nThe Way",
    ...         ]
    ...     }
    ... )
    >>> df.with_columns(
    ...     pl.col("lines").str.extract(r"(?m)^(T\w+)", 1).alias("matches"),
    ... )
    shape: (2, 2)
    ┌─────────┬─────────┐
    │ lines   ┆ matches │
    │ ---     ┆ ---     │
    │ str     ┆ str     │
    ╞═════════╪═════════╡
    │ I Like  ┆ Those   │
    │ Those   ┆         │
    │ Odds    ┆         │
    │ This is ┆ This    │
    │ The Way ┆         │
    └─────────┴─────────┘

    See the regex crate's section on `grouping and flags
    <https://docs.rs/regex/latest/regex/#grouping-and-flags>`_ for
    additional information about the use of inline expression modifiers.

    Returns
    -------
    Expr
        Expression of data type :class:`Utf8`. Contains null values if original
        value is null or the regex captures nothing.

    Examples
    --------
    >>> df = pl.DataFrame(
    ...     {
    ...         "url": [
    ...             "http://vote.com/ballon_dor?error=404&ref=unknown",
    ...             "http://vote.com/ballon_dor?ref=polars&candidate=messi",
    ...             "http://vote.com/ballon_dor?candidate=ronaldo&ref=polars",
    ...         ]
    ...     }
    ... )
    >>> df.select(
    ...     pl.col("url").str.extract(r"candidate=(\w+)", 1).alias("candidate"),
    ...     pl.col("url").str.extract(r"ref=(\w+)", 1).alias("referer"),
    ...     pl.col("url").str.extract(r"error=(\w+)", 1).alias("error"),
    ... )
    shape: (3, 3)
    ┌───────────┬─────────┬───────┐
    │ candidate ┆ referer ┆ error │
    │ ---       ┆ ---     ┆ ---   │
    │ str       ┆ str     ┆ str   │
    ╞═══════════╪═════════╪═══════╡
    │ null      ┆ unknown ┆ 404   │
    │ messi     ┆ polars  ┆ null  │
    │ ronaldo   ┆ polars  ┆ null  │
    └───────────┴─────────┴───────┘

In [161]:
df.with_columns(
    pl.col('birthday').dt.date().alias('date2')
)

shape: (4, 6)
┌─────┬──────┬─────────────────────┬────────┬────────────────────┬────────────┐
│ idx ┆ name ┆ birthday            ┆ gender ┆ bio                ┆ date2      │
│ --- ┆ ---  ┆ ---                 ┆ ---    ┆ ---                ┆ ---        │
│ i64 ┆ str  ┆ datetime[μs]        ┆ str    ┆ str                ┆ date       │
╞═════╪══════╪═════════════════════╪════════╪════════════════════╪════════════╡
│ 1   ┆ 张三 ┆ 2009-05-01 00:00:00 ┆ 男     ┆ 好好学习，天天向上 ┆ 2009-05-01 │
│ 2   ┆ 李四 ┆ 2005-10-15 00:00:00 ┆ 男     ┆ 泰难了             ┆ 2005-10-15 │
│ 3   ┆ 王五 ┆ 2000-12-31 00:00:00 ┆ 男     ┆ 学习有毛用         ┆ 2000-12-31 │
│ 4   ┆ 赵六 ┆ 1995-06-15 00:00:00 ┆ 女     ┆ 躺平ing            ┆ 1995-06-15 │
└─────┴──────┴─────────────────────┴────────┴────────────────────┴────────────┘

In [168]:
q = (
    df.lazy()
    .groupby('gender')
    .agg(
        pl.count(),
        pl.col('bio').str.len_chars().mean().alias('mean_len')
    )
)

q.collect()

/var/folders/y0/4gqxky0s2t94x1c1qhlwr6100000gn/T/ipykernel_61402/150976223.py:3: DeprecationWarning: `groupby` is deprecated. It has been renamed to `group_by`.
  .groupby('gender')

shape: (2, 3)
┌────────┬───────┬──────────┐
│ gender ┆ count ┆ mean_len │
│ ---    ┆ ---   ┆ ---      │
│ str    ┆ u32   ┆ f64      │
╞════════╪═══════╪══════════╡
│ 男     ┆ 3     ┆ 5.666667 │
│ 女     ┆ 1     ┆ 5.0      │
└────────┴───────┴──────────┘

In [169]:
df.groupby('gender').agg(
    pl.count(),
    pl.col('bio').str.len_chars().mean().alias('mean_len')
)

/var/folders/y0/4gqxky0s2t94x1c1qhlwr6100000gn/T/ipykernel_61402/2152217435.py:1: DeprecationWarning: `groupby` is deprecated. It has been renamed to `group_by`.
  df.groupby('gender').agg(

shape: (2, 3)
┌────────┬───────┬──────────┐
│ gender ┆ count ┆ mean_len │
│ ---    ┆ ---   ┆ ---      │
│ str    ┆ u32   ┆ f64      │
╞════════╪═══════╪══════════╡
│ 女     ┆ 1     ┆ 5.0      │
│ 男     ┆ 3     ┆ 5.666667 │
└────────┴───────┴──────────┘